safe:      true
permalink: pretty
exclude:   [ README.md, Gemfile, vendor, .*, bower.json ]

# Setup
title: "William Durand"
tagline: ""
description: |
  Hi! I'm <a href="https://www.twitter.com/couac">Will</a>.
  <br>
  <br>
  Lifelong learner. OSS evangelist. Traveler. (Runner.) Speaker. Web worker at Mozilla. He/him.
  <br>
  <br>
  <small>
  <a href="mailto:will@drnd.me">will@drnd.me</a> | <a href="http://pgp.mit.edu/pks/lookup?op=get&search=0xa509bcf1c1274f3b">0xa509bcf1c1274f3b</a>
  </small>

# Used in Atom feeds
url: "https://williamdurand.fr"

# About/contact
author:
  name: William Durand
  email: will@drnd.me


my_github:   https://www.github.com/willdurand
my_twitter:  https://www.twitter.com/couac

#global_message:

gems:
  - jemoji
